title: Mathew Chase Projects Portfolio
description: This page showcases a professional portfolio of personal cybersecurity projects, security awareness initiatives, scripting, home labs, and technical documentation.
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
